feat: allow multiple target_regions BED files defined in config.yaml, merging them into one
snakemake-workflows/dna-seq-varlociraptor pull request #161
Opened 2022-09-05 10:14 UTC by dlaehnemann

2022-09-12 11:15 UTC, johanneskoester requested changes
Nice! Just one minor thing.

2022-09-12 11:15 UTC, johanneskoester commented on workflow/rules/regions.smk
> +        config["target_regions"] if "target_regions" in config else [],
```suggestion
        config.get("target_regions", []),
```

2022-09-12 11:54 UTC, dlaehnemann commented
Done, feel free to merge once the tests passed.

2022-09-23 09:11 UTC, johanneskoester approved these changes

2022-09-23 11:10 UTC, johanneskoester approved these changes

2022-09-23 19:34 UTC, merged