Call consensus reads
snakemake-workflows/dna-seq-varlociraptor pull request #56
Opened 2020-11-11 15:21 UTC by FelixMoelder

This PR adds a rule for calling rbt consensus reads.

Currently, only overlapping reads are going to be merged, while duplicates remain separated.

While the current behavior is supposed for panel data we could optionally add an additional rule annotation reads duplicate groups.
In case that rule would be activated consensus read calling would also merge duplicates into a single read.
Which might be useful to improve read quality instead of dropping duplicates.

2020-12-15 14:50 UTC, FelixMoelder commented
Reminder for myself:
Environments for rbt and varlociraptor needs to be updated when new releases are available.
These include handling of strand information

2021-01-28 12:18 UTC, FelixMoelder commented
Todo: Template for `rbt vcf-report` needs to be updated to working with the latest rbt version.

2021-02-03 10:20 UTC, FelixMoelder commented
The custom report template has been removed.
Instead all modifications of the default template have been moved in a separate file by @fxwiegand.
Moving modifications also allows using the latest version of the default template including several bug fixes and improvement.
Future changes to the `rbt vcf-report` template will be directly included when every the rbt dependency gets updated.

2021-02-22 08:29 UTC, johanneskoester requested changes

2021-02-22 08:29 UTC, johanneskoester commented on .test/config-chm-eval/config.yaml
> +    max_depth: "200"
```suggestion
    max_depth: 200
```

2021-02-22 08:29 UTC, johanneskoester commented on .test/config-no-candidate-filtering/config.yaml
> +    max_depth: "200"
```suggestion
    max_depth: 200
```

2021-02-22 08:29 UTC, johanneskoester commented on .test/config-sra/config.yaml
> +    max_depth: "200"
```suggestion
    max_depth: 200
```

2021-02-22 08:29 UTC, johanneskoester commented on .test/config/config.yaml
> +    max_depth: "200"
```suggestion
    max_depth: 200
```

2021-02-22 08:29 UTC, johanneskoester commented on .test/config_primers/config.yaml
> +    max_depth: "200"
```suggestion
    max_depth: 200
```

2021-02-22 08:29 UTC, johanneskoester commented on config/config.yaml
> +    max_depth: "200" # Set when processing panel data with high coverage
```suggestion
    max_depth: 200 # Set to desired depth when processing panel data with high coverage
```

2021-02-22 08:29 UTC, johanneskoester commented on workflow/envs/varlociraptor.yaml
> +  - varlociraptor =2.6.0
```suggestion
  - varlociraptor =2.6.1
```

2021-02-22 08:29 UTC, johanneskoester commented on workflow/rules/annotation.smk
> +        extra="-Xmx4g", #Never used
```suggestion
```

2021-02-22 08:29 UTC, johanneskoester commented on workflow/rules/calling.smk
> +        max_depth="--max-depth {}".format(config["params"]["varlociraptor_preprocess"].get("max_depth", "200"))
```suggestion
        max_depth="--max-depth {}".format(config["params"]["varlociraptor_preprocess"].get("max_depth", 200))
```

2021-02-22 08:29 UTC, johanneskoester commented on workflow/rules/report.smk
> +    threads: 8
Move threads directly above shell. Not enforced by snakefmt yet, but this is more consistent.

2021-02-22 08:29 UTC, johanneskoester commented on workflow/schemas/config.schema.yaml
> +  calc_consensus_reads:
Also add the max_depth setting in case it is still missing.

2021-02-22 10:53 UTC, FelixMoelder commented
Suggested changes have been collectively added in a single commit.

2021-02-22 11:22 UTC, johanneskoester approved these changes

2021-02-22 11:22 UTC, merged