Tables
snakemake-workflows/dna-seq-varlociraptor pull request #58
Opened 2020-11-13 23:26 UTC by christopher-schroeder

Allow the generation of table-like tsv and excel files for detected variants.

2020-11-16 16:00 UTC, johanneskoester requested changes
Awesome, thanks a lot! Just one thing below.

2020-11-19 17:52 UTC, christopher-schroeder commented on workflow/rules/common.smk
> +                            event=config["calling"]["fdr-control"]["events"]))
Oh no it was not a duplication, but should access the generate_excel flag. So if the table generation is activate and also this flag is activate, then xlsx files are generated additionally to the tsv files.

2020-11-25 09:56 UTC, johanneskoester approved these changes

2020-11-25 09:56 UTC, merged

2020-12-03 13:29 UTC, tedil commented on workflow/rules/common.smk
> +    return ", ".join(expression)
This should use the expression supplied in `config.yaml`
```suggestion
def get_vembrane_expression(wc):
    expression = (
        config["tables"]
        .get("output", {})
        .get(
            "expression",
            "INDEX, CHROM, POS, REF, ALT[0], ANN['Consequence'], ANN['IMPACT'], ANN['SYMBOL'], ANN['Feature']",
        )
    )
    parts = [expression]
    if config["tables"].get("output", {}).get("event_prob", False):
        parts.append(
            ", ".join(
                f"1-10**(-INFO['PROB_{x.upper()}']/10)"
                for x in config["calling"]["fdr-control"]["events"][wc.event][
                    "varlociraptor"
                ]
            )
        )
    if config["tables"].get("output", {}).get("genotype", False):
        parts.append(
            ", ".join(
                f"FORMAT['AF']['{sample}']" for sample in get_group_sample_aliases(wc)
            )
        )
    if config["tables"].get("output", {}).get("depth", False):
        parts.append(
            ", ".join(
                f"FORMAT['DP']['{sample}']" for sample in get_group_sample_aliases(wc)
            )
        )
    return ", ".join(parts)
```